# For more information about the configurations used
# in this file, please see the GitHub actions documentation.
#
# https://help.github.com/en/github/automating-your-workflow-with-github-actions/

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Validate Markdown
        run: npm run lint-markdown
        if: github.event_name != 'schedule'

      - name: Check links
        run: npm run check-links
        if: github.event_name == 'schedule'

name: test

on:
  push:
  schedule:
    # Schedule workflow to run every week on Friday at 8pm.
    - cron: "0 0 * * SAT"
